Repository EESSI/eessi-bot-software-layer, pull requests merged in 2022-11, with the labels that each got.

#56 add `run_cmd` method
  tasks/build.py
  tests/test_task_build.py
Labels: priority:high, code_cleanup

#69 Pass flake8 tests for tests/test_task_build.py
  tests/test_task_build.py
Labels: code_cleanup

#65 Pass flake8 tests for tools/args.py
  tools/args.py
Labels: code_cleanup

#66 Pass flake8 tests for tools/config.py
  tools/config.py
Labels: code_cleanup

#67 Pass flake8 tests for tools/logging.py
  tools/logging.py
Labels: code_cleanup

#62 working implementation of 'deploy' step
  README.md
  app.cfg.example
  eessi_bot_event_handler.py
  eessi_bot_job_manager.py
  tasks/build.py
  tasks/deploy.py
Labels: enhancement, priority:high

#80 split up option parsers for event handler and job manager
  eessi_bot_event_handler.py
  eessi_bot_job_manager.py
  tools/args.py
Labels: code_cleanup
