Repository EESSI/eessi-bot-software-layer, pull requests merged in 2024-01, with the labels that each got.

#237 New bot command `bot: status`
  eessi_bot_event_handler.py
  tasks/build.py
Labels: enhancement, feature

#238 renew GitHub access token ahead of time to prevent "`Bad credentials`" crashes
  connections/github.py
Labels: bug

#240 release v0.3.0
  RELEASE_NOTES
  connections/github.py
  eessi_bot_event_handler.py
  tasks/build.py
Labels: release
