Repository EESSI/eessi-bot-software-layer, pull requests merged in 2024-02, with the labels that each got.

#247 add function that reads PR section from job metadata and use it in job manager
  eessi_bot_job_manager.py
  tests/test_eessi_bot_job_manager.py
  tests/test_tools_job_metadata.py
  tools/job_metadata.py
Labels: difficulty:easy, refactoring

#249 add function to determine comment id for a job and use it
  tasks/deploy.py
Labels: enhancement, priority:medium, difficulty:easy

#253 add PR comment id to uploaded metadata
  scripts/eessi-upload-to-staging
  tasks/deploy.py
Labels: enhancement, priority:medium, difficulty:easy

#255 fix for job manager crash: Unable to contact slurm controller
  eessi_bot_job_manager.py
Labels: difficulty:easy, priority:high, bug

#254 make upload directory in S3 bucket configurable
  README.md
  app.cfg.example
  scripts/eessi-upload-to-staging
  tasks/build.py
  tasks/deploy.py
Labels: enhancement, difficulty:medium, priority:high, refactoring

#257 only respond to bot commands
  eessi_bot_event_handler.py
  tools/commands.py
Labels: enhancement, priority:medium, difficulty:easy

#258 release notes for v0.4.0
  RELEASE_NOTES
Labels: enhancement, difficulty:easy, priority:high, bug, release

#260 improve release notes for v0.4.0
  RELEASE_NOTES
Labels: release

#259 release v0.4.0
  README.md
  RELEASE_NOTES
  app.cfg.example
  eessi_bot_event_handler.py
  eessi_bot_job_manager.py
  scripts/eessi-upload-to-staging
  tasks/build.py
  tasks/deploy.py
  tests/test_eessi_bot_job_manager.py
  tests/test_tools_job_metadata.py
  tools/commands.py
  tools/job_metadata.py
  tools/pr_comments.py
Labels: release
